// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BankAccountKataWebAPI.BankAccountDb
{
    public partial class BankAccountDbContext : DbContext
    {
        public BankAccountDbContext()
        {
        }

        public BankAccountDbContext(DbContextOptions<BankAccountDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<History> History { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Accounts>(entity =>
            {
                entity.HasKey(e => e.Name)
                    .HasName("PK__ACCOUNTS__D9C1FA01950FF133");

                entity.ToTable("ACCOUNTS");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NAME");

                entity.Property(e => e.Balance).HasColumnName("BALANCE");
            });

            modelBuilder.Entity<History>(entity =>
            {
                entity.HasKey(e => new { e.Name, e.Date, e.Amount, e.Balance })
                    .HasName("PK__HISTORY__ACDF471120692552");

                entity.ToTable("HISTORY");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NAME");

                entity.Property(e => e.Date)
                    .HasColumnType("datetime")
                    .HasColumnName("DATE");

                entity.Property(e => e.Amount).HasColumnName("AMOUNT");

                entity.Property(e => e.Balance).HasColumnName("BALANCE");

                entity.Property(e => e.Operation)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("OPERATION");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}