// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankAccountKataGrpc.Host.BankAccountDb
{
    public partial class Accounts
    {
        public string Name { get; set; }
        public double Balance { get; set; }
    }
}